"""Hatchling build hook that includes compiled pybind11 extensions and generated
protobuf modules in the wheel.

Neither compiled extensions (.so/.pyd) nor generated protobuf files (*_pb2.py)
are tracked by git, so hatchling's default VCS-based file selection excludes
them.  This hook:
  1. Scans the source tree for .so / .pyd files and *_pb2.py files.
  2. Adds them to force_include so they are copied into the wheel verbatim.
  3. Sets pure_python = False so the wheel is tagged cp<N>-cp<N>-<platform>
     instead of py3-none-any (only when native extensions are present).

Usage in CI:
    1. Build the extension with Bazel.
    2. Copy the output binary into the source tree (make copy_extensions_local).
    3. Run `uv build --wheel` — this hook fires and packages everything.
"""

import glob

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class CustomBuildHook(BuildHookInterface):
    def initialize(self, version, build_data):
        if self.target_name != "wheel":
            return

        native_exts = []
        for ext in ("so", "pyd"):
            native_exts.extend(
                glob.glob(f"src/pysc2_evolved/**/*.{ext}", recursive=True)
            )

        if native_exts:
            build_data["pure_python"] = False
            build_data["infer_tag"] = True

        # *_pb2.py files are generated by protoc and gitignored; include them
        # the same way as compiled extensions.
        pb2_files = glob.glob("src/pysc2_evolved/**/*_pb2.py", recursive=True)

        for src_path in native_exts + pb2_files:
            # Strip the leading "src/" so the wheel path mirrors the import path.
            # e.g. src/pysc2_evolved/env/.../converter_pb2.py
            #   -> pysc2_evolved/env/.../converter_pb2.py
            wheel_path = src_path.replace("\\", "/").removeprefix("src/")
            build_data["force_include"][src_path.replace("\\", "/")] = wheel_path
